SELECT
   PS.SID,
   DECODE(SERVER_SET, NULL, 'COORDINATOR', 1, '  CONSUMER',
     '    PRODUCER') ROLE,
   DECODE(SW.WAIT_TIME, 0, SW.EVENT, 'CPU') ACTION,
   SQ.SQL_TEXT
FROM
   V$PX_SESSION PS,
   V$SESSION_WAIT SW,
   V$SQL SQ,
   V$SESSION S,
   AUDIT_ACTIONS AA
WHERE
   PS.SID = SW.SID AND
   S.SID = PS.SID AND
   S.SQL_ADDRESS = SQ.ADDRESS (+) AND
   AA.ACTION = S.COMMAND
ORDER BY PS.QCSID, NVL(PS.SERVER#, 0), PS.SERVER_SET;
